=== ChandanaMN246/JAVA/a1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT book_catalog (book+)>
<!ELEMENT book (bid,btitle, bauthor,bpublisher,bprice,bedition,quantity)>
<!ELEMENT bid (#PCDATA)>
<!ELEMENT btitle (#PCDATA)>
<!ELEMENT bauthor (#PCDATA)>
<!ELEMENT bpublisher (#PCDATA)>
<!ELEMENT bprice (#PCDATA)>
<!ELEMENT bedition (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>

=== ChandanaMN246/JAVA/a1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book_catalog SYSTEM "a1.dtd">
<book_catalog>
	<book>
		<bid>101</bid>
		<btitle>JavaProgramming</btitle>
		<bauthor>Jamea S Gosling</bauthor>
		<bpublisher>Mc Graw Hill</bpublisher>
		<bprice>450</bprice>
		<bedition>2022</bedition>
		<quantity>25</quantity>
	</book>
	<book>
		<bid>102</bid>
		<btitle>C Programming</btitle>
		<bauthor>Denis</bauthor>
		<bpublisher>Mc Graw Hill</bpublisher>
		<bprice>245</bprice>
		<bedition>2020</bedition>
		<quantity>20</quantity>
	</book>
</book_catalog>
